language: rust

rust:
  - nightly

before_install:
  - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -

script:
    - export CARGO_INCREMENTAL=0
    - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
    - cargo clean
    - cargo build --verbose $CARGO_OPTIONS
    - cargo test --verbose $CARGO_OPTIONS
    - cargo fmt -- --check
    - |
      zip -0 ccov.zip `find . \( -name "terminus*.gc*" \) -print`;
      ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
      bash <(curl -s https://codecov.io/bash) -f lcov.info;
notifications:
  irc:
    channels:
      - "chat.freenode.net##terminusdb"
    on_success: never
  slack:
    rooms:
      secure: Zshj9zGozlzkeAvsLHIH7ibMBC+//R0rz0zUbv9iA5pJ/U+oT7Hp3wAlJrehENZQNvcAfxjxvqQmWLjFRpEyqkuRRt3Luex1wNDMjAT5F1sC6X6C+3zLJXh+tjoEFWEJjj5Q1caFK/q9X6nlfjOxGYisdIZ3BdfJERR2tw9avspR6UKDsAmEEkwTLF/NF+LYFKvMkTdChf0gyA8q603O1hyodx4EU+1bmVv7t9pcxCdY2zQO3mLMO4WmzaqT2+6eaigSd7TXEcmZFBwvFn7r9polhJ0kbYQu6YIJQDqhKlDqpr45M/AgcaLiBca7gTPMCRAyJjWhjNrx7eUVE7+H5ip2i2QtA07UnvySXkdSfM0xxyqauJG2eke8N9xLRQ5teIzNmi51RuZ2ppzpXvcXqeg8eXEL30qVEr/cA7LWh+xytEUHaxOU2pujCUI9whwcWqK5ucNdGc2SISO85NiIF4SUGPmsNIBqIbWYqlrio0m1v2lOaHWKdAerJOacAHEGO127CowNQNBVkXDAfJysMIsOuQp8V7yPleVNZJSYkvmRoYNtDF1LAKnWkB3MkgNWoAj+rZm2FYEEx70jiu254Y1Fkv765hxu4V5fSGhzbGxulcss3RDOzGGLkydPBKoXXOobY9/DpdgVI1keVc2CeRbp/KuM6Fjs+Yfa3QejI1w=
