[package]
name = "ferricstore"
version = "0.1.0"
authors = ["Matthijs van Otterdijk <matthijs@datachemist.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
futures = "0.1.28"
tokio = "0.1.21"
tokio-io = "0.1.12"
bytes = "0.4.12"
memmap = "0.7"

[dev-dependencies]
tempfile = "3.1"